config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'shop' => 'pages#shop'

    resources :carts
    resources :product_items
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many  :product_items,  dependent: :destroy
    
    def add_product(product_id)
        current_item = product_items.find_by(product_id: product_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = product_items.build(product_id: product_id)
        end
        current_item
    end
    
    def total_price
      product_items.to_a.sum{|item| item.total_price}
    
    end
                
end

app/models/product.rb
class Product < ActiveRecord::Base
    before_destroy :ensure_not_product_item
    
    has_many :product_items
    
    validates  :title, :description, presence: true
    validates  :price, numericality: {greater_than_or_equal_to: 0.01}
    validates  :title, uniqueness: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  
  def ensure_not_product_item
      if product_items.empty?
          return true
      else
          errors.add(:base, 'You have Product Items')
          return false
      end
  end
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :destroy]
    rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
    
    def new
        @cart = Cart.new
    end
    
    def show
        
    end
    
    def destroy
        @cart.destroy if @cart.id == session[:cart_id]
        session[:card_id] = nil
        redirect_to shop_url, notice: 'Your Cart is Empty'
        
    end
    
    private
    
    def set_cart 
        @cart = Cart.find(params[:id])
    end
    
    def cart_params
        params[:cart]
    end
    
    def invalid_cart
        logger_error 'You trying to access invalid cart'
        redirect_to shop_url, notice: 'Invalid Cart'
    end
end

app/controllers/concerns/current_cart.rb
module  CurrentCart
    
    private 
    
    def set_cart
        @cart = Cart.find(session[:cart_id])
        rescue ActiveRecord::RecordNotFound
        @cart = Cart.create
        session[:cart_id] = @cart.id
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include CurrentCart
  before_action  :set_cart, only: [:index, :shop]
  
  def index
    @products = Product.all
  end
  
  def shop
    @products = Product.all
  end
end

app/controllers/product_items_controller.rb
class ProductItemsController < ApplicationController
    include CurrentCart
    before_action :set_cart, only: [:create]
    before_action :set_product_item, only: [:show, :destroy]
    
    def create
        product = Product.find(params[:product_id])
        @product_item = @cart.add_product(product.id)
        if @product_item.save
            redirect_to shop_url, notice: 'Product added to Cart'
        else 
            render :new
        end
    end
    
    private
    
    def set_product_item
        @product_item = ProductItem.find(params[:id])
    end
    
    def product_item_params
        params.require(:product_item).permit(:product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carts/_cart.html.erb
 <% @cart.product_items.each do |item | %>
   <ul>
      <li>
    	
    	<%= item.quantity %>&times;<%= item.product.title %>
    	<%= number_to_currency item.total_price %>
      </li>	

  </ul>
<% end %>

app/views/carts/show.html.erb
<header class="secondary">
				<div class="background-image-holder parallax-background overlay">
		    	<%= image_tag('bg-5.jpg', class: 'background-image', alt: 'Background') %>
				</div>

				<div class="container align-vertical hero">
					<div class="row">
						<div class="col-md-5 text-left">
							<h1>Your Cart</h1>
							<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</header>
			
			<section class="product-list">
				<div class="container">
				    
				<div class="container">
				    <div class="col-md-12">
				        <h2>Cart Details</h2>
				        <br>
				       <%= render 'carts/cart' %>
				       <br>
				       <h5>Total: <%= number_to_currency @cart.total_price %></h5>
				       <br>
				       <%= link_to 'Back to Store', shop_path %><br>
				       <%= link_to 'Empty Your Cart', @cart, method: :delete, data: {confirm: 'Are You Sure?'} %>
				    </div>
				</div>
				</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecomesapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Raleway:400,700,600,500,300'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<%= render 'shared/header' %>
	<%= render 'shared/message' %>
	
		<div class="main-container">
			
			<%= yield %>
		
        <%= render 'shared/footer' %>
			
		</div><!-- /.main-container -->
			

</body>
</html>

app/views/pages/index.html.erb
	<header class="fullscreen-element">
				<div class="background-image-holder parallax-background overlay">
					<%= image_tag('bg-7.jpg', class: 'background-image', alt: 'Background')%>
			
				</div>

				<div class="container align-vertical hero">
					<div class="row">
						<div class="col-md-5 col-sm-5 col-md-offset-7 col-sm-offset-7 text-left">
							<h1>Modern Store</h1>
							<p>This is the modern store where you can buy one and and get a free popcorn plus free delivery.</p>
							<div class="button-group">
							  <%= link_to 'Shop Now', root_path, class: "btn btn-primary" %>
							</div>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
				
			</header>

			<div class="action-bar">
				<div class="container">
					<div class="row">
						<div class="col-sm-4">
							<%= link_to root_path do %>
						   <span data-icon="v" class="icon"></span> <span class="text">Fast Delivery</span>
						   <% end %>
						</div>
						<div class="col-sm-4">
							<%= link_to root_path do %>
							<span data-icon="/" class="icon"></span> <span class="text">Adjustable</span>
							<% end %>
						</div>
						<div class="col-sm-4">
					    	<%= link_to root_path do %>
						    <span data-icon="7" class="icon"></span> <span class="text">Inovative</span>
						   <% end %>
						</div>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</div>

			<section>
				<div class="background-image-holder overlay" >
					<%= image_tag('bg-2.jpg', class: 'background-image', alt: 'Background')%>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-sm-5 text-left">
							<h2 class="page-title">For your familly</h2>
							<p class="description"> This is the modern store where you can buy one furniture and and get a free popcorn plus free delivery.</p>
							<%= link_to 'Shop Now', root_path, class: 'btn btn-primary' %>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>

			
			
			 <br>
			<h2 class="page-title text-center">Featured Products</h2>
        
        <%= render 'shared/list' %>

			<section>
				<div class="background-image-holder on-page overlay">
					<%= image_tag('bg-3.jpg', class: 'background-image', alt: 'Background')%>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-sm-5 col-sm-offset-7 text-right">
							<h2 class="page-title">Modern Store<span class="accent-color">.</span></h2>
							<p class="description">This is the modern store where you can buy one and and get a free popcorn plus free delivery.</p>
							<%= link_to "Shop Now" , root_path, class: "btn btn-primary" %>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>

app/views/pages/shop.html.erb
	<header class="secondary">
				<div class="background-image-holder parallax-background overlay">
		    	<%= image_tag('bg-5.jpg', class: 'background-image', alt: 'Background') %>
				</div>

				<div class="container align-vertical hero">
					<div class="row">
						<div class="col-md-5 text-left">
							<h1>Our Shop</h1>
							<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</header>
			
			<section class="product-list">
				<div class="container">
				    <% @products.each do |product| %>
					<div class="row">
						<div class="col-md-12">
							<div class="product">
								<div class="row">
									<div class="col-md-6 col-xs-12">
										<div class="thumbnail">
										 <%= image_tag product.image %>
										</div>
									</div>
									<div class="col-md-5 col-md-offset-1">
										<div class="product-details">
											<h2 class="product-title">
											    <%= product.title %>
											</h2>
											<p class="product-price">
											 <%= number_to_currency product.price %>
											</p>
										      
											<p> 
											<%= product.description %>
											</p>
                                           <%= button_to product_items_path(product_id: product), class: 'btn btn-default' do %>
											<i class="fa fa-shopping-cart"></i> Add to cart
											<% end %>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div><!-- /.row -->
					<% end %>
					</div>
					</section>
			
			
				<div class="no-padding-top section">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<a href="#" class="load-more"><i class="fa fa-ellipsis-h"></i></a>
						</div>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</div>

app/views/shared/_footer.html.erb
	<section class="newsletter accent-bg">
				<div class="background-image-holder overlay accent" >
						<%= image_tag('bg-4.jpg', class: 'background-image', alt: 'Background')%>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-md-5 text-left">
							<h2 class="page-title">Join our newsletter</h2>
							<p>This is the modern store where you can buy one and and get a free popcorn plus free delivery.</p>
						</div>
						<div class="col-md-4">
							<form class="newsletter-form">
								<input type="text" name="email" id="email" placeholder="Your email address">
							</form>
						</div>
						<div class="col-md-3">
							<%= link_to "Join Now",root_path, class:"btn btn-primary" %>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>

			<footer class="footer">
				<div class="container">
					<div class="row">
					   <div class="col-md-6 col-md-offset-3">
						<ul class="footer-navigation">
								<li class="active">
				
							      <%= link_to 'Home', root_path %>
							   </li>
							
							      <li>
							       <%= link_to 'Store', root_path %>
						       	 </li>
							
							     <li>
							      <%= link_to 'About', root_path %>
						     	</li>
							
							      <li>
							      <%= link_to root_path do %>
							     <i class="fa fa-paper-plane"></i>Contact
							     <% end %>
							    </li>
					         
						</ul>
							<ul class="accepted-payments">
								<li>
								    <%= link_to root_path do %>
									<i class="fa fa-cc-amex"></i>
									<% end %>
								</li>
								 <li>
								    <%= link_to root_path do %>
									<i class="fa fa-cc-visa"></i>
									<% end %>
								</li>
								<li>
								     <%= link_to root_path do %>
									<i class="fa fa-cc-paypal"></i>
									<% end %>
								</li>
								  <li>
							          <%= link_to root_path do %>
								 	 <i class="fa fa-cc-stripe"></i>
									 <% end %>
								 </li>
								     <%= link_to root_path do %>
								 	 <i class="fa fa-cc-mastercard"></i>
								     <% end %>
								 </li>
							</ul>
							<div class="copyright">
								<p>Copyright © 2016 unedujoe@gmail.com</p>
							</div>
						</div>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</footer>

app/views/shared/_header.html.erb
<!-- Off screen navigation -->
    	<div id="sidr">
			<ul>	
					<li>
						<%= link_to '#', class: "side-logo" do %>
						eComesApp
						<span class="logo-dot-accent-bg"></span>
						<% end %>
					</li>
				
					<li class="active">
					    <%= link_to "Store", shop_path %>
					</li>
					
				
					<li class="divider">
						 <span></span>
					</li>
					
					<li>
					    <%= link_to 'Privacy', root_path %>
					</li>
					
					<li>
					    <%= link_to 'Terms & conditions', root_path %>
					</li>
	
			</ul>

			<div class="side-social">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-instagram"></i></a>
			</div>
		</div>

		<div class="nav-container">
			<nav class="navbar navbar-default">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-navigation" aria-expanded="false">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						
						<%= link_to root_path, class: 'navbar-brand' do %>
						Store <span class="logo-dot accent-bg"></span>
						<% end%>
						
						<a href="#sidr" class="side-menu-opener mobile">
							<div class="bars">
						        <span class="bar top"></span>
						        <span class="bar middle"></span>
						        <span class="bar bottom"></span>
						    </div>
						</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="collapse-navigation">
						<ul class="nav navbar-nav">
							<li>
							  <%= link_to 'Home', root_path %>
							</li>
							
							<li>
							  <%= link_to 'Store', shop_path %>
							</li>
							
							<li>
							  <%= link_to 'About', root_path %>
							</li>
							
							<li>
							<%= link_to root_path do %>
							  <i class="fa fa-paper-plane"></i>Contact
							  <% end %>
							 </li>
					         
					         <li>
						         	<% if @cart.total_price > 0 %>
								     <%= link_to @cart, class: 'menu-cart' do %>
								      <i class="fa fa-shopping-cart"></i> 
								      <%= number_to_currency @cart.total_price %>
								      <% end %>
								      <% else %>
								     <a href="#" class="menu-cart"><i class="fa fa-shopping-cart"></i>0.00</a>
								  <% end %>
							</li>
					
						 </ul> 
						      
						      
						
							
						<ul class="nav navbar-nav navbar-right">
							<li>
								<a href="#sidr" class="side-menu-opener">
									<div class="bars">
								        <span class="bar top"></span>
								        <span class="bar middle"></span>
								        <span class="bar bottom"></span>
								    </div>
								</a>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container -->
			</nav>
		</div>

app/views/shared/_list.html.erb
	<section class="products-grid">
				<div class="container">
					<div class="row products-container">
					    <% @products.each do |product| %>
					    <% if product.id <= 3 %>
						<div class="col-md-4 col-sm-6 col-xs-12 product">
							<div class="thumbnail" style="background-image: url('/assets/products/<%= product.image_file_name %>');">
								<div class="product-details text-center">
									<div class="align-vertical">
										<h3>
										    <%= product.title %>
										</h3>
										   <%= link_to root_path, class:"btn btn-primary" do %>
											<i class="fa fa-shopping-cart"></i> Add to cart
											<% end %>
										<p class="product-price">
										    <%= number_to_currency product.price %>
										    
										</p>
									</div>
								</div>
							</div>
						</div>
						<% end %>
					<% end %>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</section>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
       toastr['<%= type %>'] ('<%= f[1] %>')
    <% end %>
    </script>
<% end %>